# Generated by Django 4.2.1 on 2023-06-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_barang', models.CharField(max_length=20)),
                ('harga_barang', models.IntegerField()),
                ('harga_barang2', models.IntegerField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
